package main

import (
	"context"
	_ "embed"
	"errors"
	"net"
	"os"
	"os/signal"
	"syscall"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/log"
	"github.com/charmbracelet/ssh"
	"github.com/charmbracelet/wish"
	"github.com/charmbracelet/wish/activeterm"
	"github.com/charmbracelet/wish/bubbletea"
	"github.com/charmbracelet/wish/logging"

	"github.com/janharkonen/portfolio/apps/tui/internal/data"
	"github.com/janharkonen/portfolio/apps/tui/internal/tui"
)

// Generated from packages/app_data — regenerated by `pnpm -F tui build`.
//
//go:embed data/data.json
var rawData []byte

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func main() {
	appData, err := data.Parse(rawData)
	if err != nil {
		log.Fatal("could not parse embedded data.json", "error", err)
	}

	host := envOr("TUI_HOST", "0.0.0.0")
	port := envOr("TUI_PORT", "23234")
	keyPath := envOr("TUI_HOSTKEY_PATH", ".ssh/id_ed25519")
	contactURL := envOr("TUI_CONTACT_URL", "https://janharkonen.fi/api/contact")

	srv, err := wish.NewServer(
		wish.WithAddress(net.JoinHostPort(host, port)),
		wish.WithHostKeyPath(keyPath),
		wish.WithMiddleware(
			bubbletea.Middleware(teaHandler(appData, contactURL)),
			activeterm.Middleware(),
			logging.Middleware(),
		),
	)
	if err != nil {
		log.Fatal("could not create server", "error", err)
	}

	done := make(chan os.Signal, 1)
	signal.Notify(done, os.Interrupt, syscall.SIGTERM)
	log.Info("starting SSH server", "host", host, "port", port)
	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, ssh.ErrServerClosed) {
			log.Error("could not start server", "error", err)
			done <- syscall.SIGTERM
		}
	}()

	<-done
	log.Info("stopping SSH server")
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil && !errors.Is(err, ssh.ErrServerClosed) {
		log.Error("could not stop server", "error", err)
	}
}

func teaHandler(d data.Data, contactURL string) bubbletea.Handler {
	return func(s ssh.Session) (tea.Model, []tea.ProgramOption) {
		pty, _, _ := s.Pty()
		// Per-session renderer so styles degrade to the client's color profile.
		renderer := bubbletea.MakeRenderer(s)
		m := tui.New(d, renderer, contactURL, pty.Window.Width, pty.Window.Height)
		return m, []tea.ProgramOption{tea.WithAltScreen()}
	}
}
